#!/bin/bash


# UTILITY FUNCTIONS

cleanup() {
    pactl unload-module $module_id
    killall -q parec lame
    exit 0
}

function require {
    hash $1 2>/dev/null || {
	echo >&2 "Error: '$1' is required, but was not found."; exit 1;
    }
}


# SETUP

# Check if arguments given
if [[ -z "$1" ]]; then
    # No arguments given
    echo "Entra el nom de la biblioteca"
    exit 1
fi


# Assert standard Unix utilities are available.
require grep
require pulseaudio
require lame
require spotify
#require eyed3


default_output=$(pacmd list-sinks | grep -A1 "* index" | grep -oP "<\K[^ >]+")
default_output_index=$(pacmd list-sinks | grep "* index" | awk -F ': ' '{print $2}') 

module_id=$(pactl load-module module-combine-sink sink_name=record-n-play slaves=$default_output sink_properties=device.description="Record-and-Play")

# Agafem l'index del sink-input Spotify i l'afegim al combined sink
index=$(pacmd list-sink-inputs | grep -B15 Spotify | grep index: | awk -F ': ' '{print $2}')
pactl move-sink-input $index record-n-play

# El combined sink tendeix a convertirse en el default system output device. Ho revertim
pacmd set-default-sink $default_output_index

# Exportem les variables perque les pugui fer servir cleanup
export module_id



trap "cleanup" SIGINT SIGTERM


# MAIN

first=true
while true
do
    eval $(./sp eval)
    
    if [[ $prev_title != "$SPOTIFY_TITLE" || $first = true ]]; then	
	if [[ $first != true ]]; then
	    # Afegim a l'anterior canço la seva caràtula
	    eyeD3 --add-image "$folder/$cover_name:FRONT_COVER" "$folder/${prev_title}.mp3"

	    echo "Canvi de canço"
	    killall -q parec lame
	fi
	first=false

	# Creem variable amb la ruta del directori corresponent
	folder="$1/$SPOTIFY_ARTIST/$SPOTIFY_ALBUM///" # Les tres / son per identificar el nom de l'album cover posteriorment
	
	# Mirem que el fitxer no existeixi
	existeix=false
	for f in ${folder}/*.mp3
	do
	    if [[ ${f/$folder'/'/} = ${SPOTIFY_TITLE}.mp3 ]]
	    then existeix=true
		 break
	    fi
	done
	
	# Si és un anunci no l'enregistrem
	if [[ $SPOTIFY_TRACKID == "spotify:ad:"* ]]; then
	    anunci=true
	    echo -e "Anunci\n"
	else
	    anunci=false
	fi
	
	
	if [[ $existeix = false && $anunci = false ]]; then
	    mkdir -p "$folder"

	    #sleep 1
	    echo -e "Enregistrant: $SPOTIFY_TITLE\n"
            parec --format=s16le -d record-n-play.monitor | \
	    lame --tt "$SPOTIFY_TITLE"               \
		 --ta "$SPOTIFY_ARTIST"              \
		 --tl "$SPOTIFY_ALBUM"               \
		 --tn "$SPOTIFY_TRACKNUMBER"         \
		 -r -q 3 --abr 192 - "$folder/${SPOTIFY_TITLE}.mp3" > /dev/null &1>/dev/null

	    # Descarreguem l'album cover
	    cover_name=$(glyrc cover --artist "$SPOTIFY_ARTIST" --album "$SPOTIFY_ALBUM" -w "$folder" 2>&1 >/dev/null \
			     | grep -F "$folder" `# -F també busca caràcters especials`  \
			     | awk -F '///' '{print $2}' \
			     | sed s'/.$//')
	    
	elif [[ $existeix = true ]]; then
	    echo -e "La canço \"$SPOTIFY_TITLE\", ja existeix\n"
	fi
    fi
    prev_title=$SPOTIFY_TITLE
done
